[build]
base = "/"
publish = 'dist/'
functions = "functions/"

[[redirects]]
from = "https://fvs.io/*"
to="*"
status = 404
force = true


[[redirects]]
from = "https://fvs.io/*"
to="/*"
status = 302
force = true
